apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel.fullname" . }}-collector-config
data:
  collector.yaml: |
    receivers:
      {{- if .Values.collector.config.receivers }}
        {{- toYaml .Values.collector.config.receivers | nindent 6 }}
      {{- else }}
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      {{- end }}

    processors:
      {{- if .Values.collector.config.processors }}
        {{- toYaml .Values.collector.config.processors | nindent 6 }}
      {{- else }}
      filter:
        metrics:
          datapoint:
            - 'attributes["http.target"] == "/api/health"'
      {{- end }}

    exporters:
      {{- if .Values.collector.config.exporters }}
        {{- toYaml .Values.collector.config.exporters | nindent 6 }}
      {{- else }}
      prometheus:
        endpoint: 0.0.0.0:{{ .Values.collector.containerPort }}
        resource_to_telemetry_conversion:
          enabled: true
      {{- end }}

    service:
      {{- if .Values.collector.config.service }}
        {{- toYaml .Values.collector.config.service | nindent 6 }}
      {{- else }}
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [filter]
          exporters: [prometheus]
      {{- end }}
