apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "otel.fullname" . }}-collector-config'
  labels:
    {{- include "otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
data:
  collector.yaml: |
    receivers:
      {{- if .Values.collector.config.receivers }}
        {{- toYaml .Values.collector.config.receivers | nindent 6 }}
      {{- else }}
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.collector.receivers.grpc.port }}
          http:
            endpoint: 0.0.0.0:{{ .Values.collector.receivers.http.port }}
      {{- end }}

    processors:
      {{- if .Values.collector.config.processors }}
        {{- toYaml .Values.collector.config.processors | nindent 6 }}
      {{- else }}
      filter:
        metrics:
          datapoint:
            - 'attributes["http.target"] == "/api/health"'
      tail_sampling:
        policies:
          - name: drop-health
            type: string_attribute
            string_attribute:
              key: http.target
              values: ["/health"]
              invert_match: true
      {{- end }}

    exporters:
      {{- if .Values.collector.config.exporters }}
        {{- toYaml .Values.collector.config.exporters | nindent 6 }}
      {{- else }}
      prometheus:
        endpoint: 0.0.0.0:{{ .Values.collector.exporters.port }}
        resource_to_telemetry_conversion:
          enabled: true
      {{- if .Values.jaeger.enabled }}
      otlp/jaeger:
        endpoint: {{ include "otel.fullname" . }}-jaeger:{{ .Values.jaeger.endpoints.grpc.port }}
        tls:
          insecure: true
      {{- end }}
      {{- end }}

    service:
      {{- if .Values.collector.config.service }}
        {{- toYaml .Values.collector.config.service | nindent 6 }}
      {{- else }}
      pipelines:
        {{- if .Values.jaeger.enabled }}
        traces:
          receivers: [otlp]
          processors: [filter, tail_sampling]
          exporters: [otlp/jaeger]
        {{- end }}
        metrics:
          receivers: [otlp]
          processors: [filter]
          exporters: [prometheus]
      {{- end }}
