apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "otel.fullname" . }}-jaeger'
  labels:
    {{- include "otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
