apiVersion: v1
kind: Service
metadata:
  name: '{{ include "otel.fullname" . }}-collector'
  labels:
    {{- include "otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  selector:
    {{- include "otel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: collector
  ports:
    - name: {{ .Values.collector.exporters.portName }}
      port: {{ .Values.collector.exporters.port }}
      targetPort: {{ .Values.collector.exporters.port }}
    - name: otlp-grpc
      port: {{ .Values.collector.receivers.grpc.port }}
      targetPort: {{ .Values.collector.receivers.grpc.port }}
    - name: otlp-http
      port: {{ .Values.collector.receivers.http.port }}
      targetPort: {{ .Values.collector.receivers.http.port }}
