apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: {{ .Values.collector.endpoints.portName }}
      port: {{ .Values.collector.containerPort }}
      targetPort: {{ .Values.collector.containerPort }}
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
