name: Package and Publish Helm Chart

on:
  push:
    branches:
      - dev
      - stage
      - "ci-test/**"
    tags: ["v*.*.*"] # vx.x.x

jobs:
  build-image:
    name: Package and Push Chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      CHART_NAME: "otel-collector"
      REGISTRY: "epfl-enac/otel-helm-chart"
    steps:
      - uses: actions/checkout@v4

      - name: Get Chart.yaml version and tag version
        shell: bash
        run: |
          CHART_VER=$(yq -r '.version' Chart.yaml)
          echo "CHART_VER=$CHART_VER" >> $GITHUB_ENV
          TAG_VER=$(echo "${GITHUB_REF_NAME}" | sed 's/^v//')
          echo "TAG_VER=$TAG_VER" >> $GITHUB_ENV

      - name: Set Helm chart version based on branch
        run: |
          if [[ "${{github.ref}}" == refs/tags/* ]]; then
            if [[ ! "$TAG_VER" != ${CHART_VER} ]]; then
              echo "Tag '${GITHUB_REF_NAME}' ($TAG_VER) does not match chart version '$CHART_VER'"
              exit 1
            fi
            CHART_VER=${{ github.ref_name }}
          fi
          if [[ "${{github.ref}}" == refs/heads/stage ]]; then
            CHART_VER="$CHART_VER$-rc.{{ github.run_number }}"
          fi
          if [[ "${{github.ref}}" == refs/heads/dev ]]; then
            CHART_VER="$CHART_VER$-dev.{{ github.run_number }}"
          fi
          if [[ "${{github.ref}}" == refs/heads/ci-test/* ]]; then
            CHART_VER="$CHART_VER$-dev.{{ github.run_number }}"
          fi
          echo "CHART_NAME=$CHART_VER" >> $GITHUB_ENV

      - name: Render Chart
        run: helm template .

      - name: Package Chart
        run: helm package --version $CHART_VER .

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Chart
        if: github.event_name != 'pull_request'
        run: helm push ${{ env.CHART_NAME }}-$CHART_VER.tgz oci://ghcr.io/${{ env.REGISTRY }}/helm
        env:
          HELM_EXPERIMENTAL_OCI: 1

      - name: Return Chart Version
        id: chart_version
        run: |
          echo "chart_version=$CHART_VER" >> $GITHUB_OUTPUT
